//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBox.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id { get; set; }
        public System.DateTime BillDate { get; set; }
        public string StudentId { get; set; }
        public int EducationalPeriodId { get; set; }
        public int SubEducationalPeriod { get; set; }
        public int BillItemId { get; set; }
        public int BillStatusId { get; set; }
        public string SettlementTransactionRef { get; set; }
        public bool IsDeleted { get; set; }
    }
}
