//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBox.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string PasswordData { get; set; }
        public string PasswordSalt { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int UserState { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public bool IsDeleted { get; set; }
    }
}
