//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBox.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinBatch
    {
        public int Id { get; set; }
        public System.DateTime BatchDate { get; set; }
        public int BatchSpace { get; set; }
        public int EducationalPeriod { get; set; }
        public int SubEducationalPeriod { get; set; }
        public bool IsDeleted { get; set; }
    }
}
