//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBox.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class PinBatchMember
    {
        public long Id { get; set; }
        public int BatchId { get; set; }
        public string PinData { get; set; }
        public bool IsUsed { get; set; }
        public System.DateTime DateUsed { get; set; }
        public string StudentId { get; set; }
        public int CredentialId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
