//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBox.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultRaw
    {
        public long Id { get; set; }
        public string StudentId { get; set; }
        public int CredentialId { get; set; }
        public int SessionId { get; set; }
        public int SubSessionId { get; set; }
        public int ClassId { get; set; }
        public int SubjectId { get; set; }
        public int AssessmentId { get; set; }
        public int FileId { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public decimal ScoreObtained { get; set; }
        public decimal ScoreTotal { get; set; }
        public bool IsDeleted { get; set; }
    }
}
