//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBox.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public int EducationalPeriodId { get; set; }
        public int SubEducationalPeriodId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public int AttendanceStatus { get; set; }
        public int ClassId { get; set; }
        public int MarkedByCredentialId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
