//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBox.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubEducationalPeriod
    {
        public int Id { get; set; }
        public string SubPeriodName { get; set; }
        public int SubPeriodOrder { get; set; }
        public int EducationalPeriodId { get; set; }
        public System.DateTime PeriodStart { get; set; }
        public System.DateTime PeriodEnd { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
