//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBox.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string CredentialId { get; set; }
        public decimal Amount { get; set; }
        public string RequestJson { get; set; }
        public string ResponseJson { get; set; }
        public string SettlementTransactionRef { get; set; }
        public int TransactionStatus { get; set; }
        public bool IsDeleted { get; set; }
    }
}
