//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdBox.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadHistory
    {
        public int Id { get; set; }
        public int CredentialId { get; set; }
        public int SubjectId { get; set; }
        public int ClassId { get; set; }
        public int AssessmentId { get; set; }
        public string RawFileName { get; set; }
        public string SystemFileName { get; set; }
        public string OperationMessages { get; set; }
        public long FileSize { get; set; }
        public int ProcessingStatus { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public System.DateTime DateProcessStart { get; set; }
        public System.DateTime DateProcessEnd { get; set; }
        public bool IsDeleted { get; set; }
    }
}
